package resources;
// Generated 09-mar-2023 22:01:34 by Hibernate Tools 4.3.1



/**
 * Modulos generated by hbm2java
 */
public class Modulos  implements java.io.Serializable {


     private Integer id;
     private String nombre;

    public Modulos() {
    }

    public Modulos(String nombre) {
       this.nombre = nombre;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }




}


